server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-simulation
          uri: lb://ms-simulation
          predicates:
            - Path=/api/simulation/**
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/users/**
        - id: ms-request
          uri: lb://ms-request
          predicates:
            - Path=/api/request/**
        - id: ms-evaluation
          uri: lb://ms-evaluation
          predicates:
            - Path=/api/evaluation/**
        - id: ms-trackingrequest
          uri: lb://ms-trackingrequest
          predicates:
            - Path=/api/trackingrequest/**
        - id: ms-totalcost
          uri: lb://ms-totalcost
          predicates:
            - Path=/api/totalcost/**